#!/bin/bash

# ignore failed commands
set +e

# change script permissions
chmod +x startup/*/*
chmod +x data/select_config.sh
chmod +x log/clean.sh
chmod +x log/save.sh
chmod +x log/fifo.sh
chmod +x startup/select_current.sh

. setenv

# set the 'gsw' alias to go to this directory
echo "alias gsw=\"cd ${GSW_HOME}; . setenv\"" >> ~/.bashrc

# TODO let operator select this
# for now use a default config file
(cd data; ./select_config.sh sample)

# select the default startup scripts
(cd startup; ./select_current.sh default)

# If we have the build tools, build everything
# If not, don't build
if [[ `command -v g++` && `command -v make` ]];
then
    make all
fi

# install grafana and InfluxDB for view applications
sudo bash app/db/grafana/install.sh
sudo bash app/db/run_influx/install.sh

# install mDNS tools (usually stock with Ubuntu)
sudo apt install avahi-daemon
sudo apt install avahi-utils
sudo systemctl enable avahi-daemon
