#!/bin/bash

# abrupt way to kill all gsw processes
# will NOT free any network / file resources first (kill those processes more gracefully)

if ! [ -v GSW_HOME ]
then
    echo environment not set, must run '. setenv' first
fi

FILE=${GSW_HOME}/startup/pidlist
if ! [ -f $FILE ]
then
    echo "no pidlist file"
    exit
else
    while read l; do
        echo "killing PID $l"
        sudo kill $l
    done <$FILE
fi

rm $FILE

# destroy shared memory
${GSW_HOME}/proc/shmctl/shmctl -off
