# Make all HTTP server applications

all: clean
	-chmod +x http_server.py
	-chmod +x setup_links.py
	mkdir links
	./setup_links.py

clean:
	-chmod -x http_server.py
	-chmod -x setup_links.py
	-rm -rf links
