# Make all application subdirs

all:
	-$(MAKE) -C log_view all
	-$(MAKE) -C mem_view all
	-$(MAKE) -C val_view all
	-$(MAKE) -C db all
	-$(MAKE) -C map all
	-$(MAKE) -C voice all
	-$(MAKE) -C propulsion all
	-$(MAKE) -C clock_view all
	-$(MAKE) -C clock_ctrl all
	-$(MAKE) -C http_server all

clean:
	-$(MAKE) -C log_view clean
	-$(MAKE) -C mem_view clean
	-$(MAKE) -C val_view clean
	-$(MAKE) -C db clean
	-$(MAKE) -C map clean
	-$(MAKE) -C voice clean
	-$(MAKE) -C propulsion clean
	-$(MAKE) -C clock_view clean
	-$(MAKE) -C clock_ctrl clean
	-$(MAKE) -C http_server clean 
