# Make all application subdirs

all:
	-$(MAKE) -C view_log all
	-$(MAKE) -C mem_view all
	-$(MAKE) -C val_view all
	-$(MAKE) -C db all
	-$(MAKE) -C map all
	-$(MAKE) -C voice all
	-$(MAKE) -C propulsion all

clean:
	-$(MAKE) -C view_log clean
	-$(MAKE) -C mem_view clean
	-$(MAKE) -C val_view clean
	-$(MAKE) -C db clean
	-$(MAKE) -C map clean
	-$(MAKE) -C voice clean
	-$(MAKE) -C propulsion clean
