all:
	sudo chmod +x start.sh
	sudo chmod +x stop.sh
	sudo chmod +x reset_admin_pwd.sh
	sudo chmod +x edit_config.sh

clean:
	sudo chmod -x start.sh
	sudo chmod -x stop.sh
	sudo chmod -x reset_admin_pwd.sh
	sudo chmod -x edit_config.sh
