# Make all process subdirs

all:
	-$(MAKE) -C decom all
	-$(MAKE) -C dlp all
	-$(MAKE) -C tool all
	-$(MAKE) -C shmctl all
	-$(MAKE) -C uplink all
	-$(MAKE) -C vcalc all

clean:
	-$(MAKE) -C decom clean
	-$(MAKE) -C dlp clean
	-$(MAKE) -C tool clean
	-$(MAKE) -C shmctl clean
	-$(MAKE) -C uplink clean
	-$(MAKE) -C vcalc clean
