### Make libraries in subdirs ###

### TODO copy libraries to bin folder

all:
	-$(MAKE) -C ldms all
	-$(MAKE) -C vcm all
	-$(MAKE) -C dls all

clean:
	-$(MAKE) -C ldms clean
	-$(MAKE) -C vcm clean
	-$(MAKE) -C dls clean
