#!/bin/bash

set -e

if ! [ -v GSW_HOME ]
then
    echo environment not set, must run '. setenv' first
fi

cd ${GSW_HOME}/startup/default

# create the pidlist file
if ! [ -f pidlist ]
then
    touch pidlist
else
    echo "GSW is already running!"
    exit
fi

# NOTE: PIDs are added to the begining of the file
#       so they are shutdown in the reverse order they started up
#       this keeps the data logger alive as long as possible

# create the system log fifo
echo "creating log FIFO"
${GSW_HOME}/log/fifo.sh -make
sleep 0.5

# start data logging process
echo "starting data logging process"
# this is a hack to redirect to a fifo pipe w/o blocking
${GSW_HOME}/proc/dlp/dlp -v | tee > ${GSW_HOME}/log/system.fifo &
#${GSW_HOME}/proc/dlp/dlp -v &
echo $! | cat - pidlist > temp && mv temp pidlist

# create shared memory
#${GSW_HOME}/proc/shmctl/shmctl -on

# start the decom process
echo "starting decom process"
${GSW_HOME}/proc/decom/decom &
echo $! | cat - pidlist > temp && mv temp pidlist

