#!/bin/bash

if ! [ -v GSW_HOME ]
then
    echo environment not set, must run '. setenv' first
    exit
fi

cd ${GSW_HOME}/startup/default

set -e

if [ -f ui_pids ]
then
    echo "UI already running!"
    exit
fi

# start InfluxDB
echo "starting InfluxDB locally"
${GSW_HOME}/app/db/run_influx/run_influx.sh > /dev/null &
echo $! >> ui_pids
sleep 3 

# clear InfluxDB
echo "clearing InfluxDB"
${GSW_HOME}/app/db/fwd_influx/clear_influx.sh

# start Grafana
echo "starting Grafana locally"
${GSW_HOME}/app/db/grafana/start.sh

# start measurement forwarding to InfluxDB
echo "starting database forwaring"
${GSW_HOME}/app/db/fwd_influx/fwd_influx &
echo $! >> ui_pids
