#!/bin/bash

if ! [ -v GSW_HOME ]
then
    echo environment not set, must run '. setenv' first
fi

cd ${GSW_HOME}/startup/default

if ! [ -f ui_pids ]
then
    echo "UI not running!"
    exit
else
    # kill local UI processes
    while read l; do
        echo "killing PID $l"
        sudo kill -s SIGINT $l
        sleep 0.5
    done <ui_pids
fi

rm ui_pids

# stop Grafana 
echo "stopping Grafana"
${GSW_HOME}/app/db/grafana/stop.sh
