# telemtry memory view

TARGET = print_gps


.PHONY: all clean

all:
	-chmod +x GPSTrack.py
	-chmod +x CreateLink.py
	-chmod +x run.sh


clean:
	-chmod -x GPSTrack.py
	-chmod -x CreateLink.py
	-chmod -x run.sh
