# Make all propulsion applications 

all:
	-$(MAKE) -C ec_cmd all
	-$(MAKE) -C ec_program all
	-$(MAKE) -C FL-1 all

clean:
	-$(MAKE) -C ec_cmd clean
	-$(MAKE) -C ec_program clean
	-$(MAKE) -C FL-1 clean
