all:
	chmod +x run_influx.sh
	chmod +x clear_influx.sh
	chmod +x remote_run.sh
	-$(MAKE) -C test all

clean:
	chmod -x run_influx.sh
	chmod -x clear_influx.sh
	chmod -x remote_run.sh
	-$(MAKE) -C test clean
