{
 "title": "3Cat2 Controller",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "Vehicle", "query": "halfcat" },
   { "name": "GroundStationIP", "query": "10.10.10.26" },
   { "name": "GroundStationPort", "query": "8080" },
   {
    "name": "Program",
    "query": "SELECT program from ec_programs"
   }
  ]
 },
 "panels": [
  { "title": "IGNITER", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  { "title": "IGNITER", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Program", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 } },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 0 } },
  {
   "title": "Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CLOCK from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Clock", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 } },
  { "title": "LINE CUTTER", "type": "cloudspout-button-panel", "gridPos": { "h": 4, "w": 2, "x": 0, "y": 3 } },
  { "title": "LINE_CUTTER", "type": "cloudspout-button-panel", "gridPos": { "h": 4, "w": 2, "x": 2, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LINE_CUTTER from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sequence Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SEQ_NUM_EC from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 3 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 3 } },
  {
   "title": "Hold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 16, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HOLD from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 } },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT VALVE_OX from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HEARTBEAT from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 6 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 14, "y": 6 } },
  { "title": "Clock", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 16, "y": 6 } },
  { "title": "Clock", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 6 } },
  {
   "title": "NITROS",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER_OX from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "NITROS",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER_OX from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logging", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 9 } },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT log FROM logs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT VALVE_FUEL from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER_OX from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2",
   "type": "cloudspout-button-panel",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER_OX from $Vehicle GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logging", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 12 } },
  {
   "title": "Force (lbs)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LC0_FORCE, LC0_FORCE_MEAN FROM $Vehicle WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}