{
 "title": "Engine Controller - Mobile",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "500ms",
 "templating": {
  "list": [
   { "name": "Vehicle", "query": "engine_controller_sim" },
   { "name": "GroundStationIP", "query": "gs.local" },
   { "name": "GroundStationPort", "query": "8080" },
   {
    "name": "Program",
    "query": "SELECT program from ec_programs"
   }
  ]
 },
 "panels": [
  {
   "title": "Clock",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CLOCK from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HOLD from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Solenoid 1", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 } },
  { "title": "Solenoid 1", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 } },
  { "title": "Solenoid 2", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 } },
  { "title": "Solenoid 2", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 } },
  { "title": "Solenoid 3", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 } },
  { "title": "Solenoid 3", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 } },
  { "title": "Igniter 1", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 } },
  { "title": "Igniter 1", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 21 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 } },
  { "title": "Buzzer", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 24 } },
  { "title": "Buzzer", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 24 } },
  {
   "title": "Sequence",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SEQ_NUM from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Program", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 27 } },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT log FROM logs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}