{
 "title": "Engine Controller",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Vehicle", "query": "engine_controller" },
   { "name": "GroundStationIP", "query": "gs.local" },
   { "name": "GroundStationPort", "query": "8080" },
   {
    "name": "Program",
    "query": "SELECT program from ec_programs"
   }
  ]
 },
 "panels": [
  { "title": "OX Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  { "title": "OX Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 } },
  {
   "title": "OX Valve",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SOLENOID_OX from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FUEL Valve",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SOLENOID_FUEL from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "OX Purge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SOLENOID_OX_PURGE from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FUEL Purge",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SOLENOID_FUEL_PURGE from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 } },
  { "title": "FUEL Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 } },
  { "title": "FUEL Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 } },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 } },
  { "title": "OX Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 } },
  { "title": "OX Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 } },
  {
   "title": "Igniter",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER_MAIN from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light Green",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LED_G from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light Yellow",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LED_Y from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Light Red",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LED_R from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 6 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 6 } },
  { "title": "OX Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 } },
  { "title": "OX Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 } },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 9 } },
  { "title": "Clock", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 9 } },
  { "title": "Igniter", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 } },
  { "title": "Igniter", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 } },
  {
   "title": "Light Buzzer",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT LED_BUZZ from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sequence",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SEQ_NUM from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HEARTBEAT from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Program", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 } },
  {
   "title": "Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CLOCK from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 12 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 12 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 } },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 15 } },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 11, "y": 15 } },
  {
   "title": "Hold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HOLD from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 } },
  { "title": "Light", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 } },
  { "title": "Buzzer", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 } },
  { "title": "Buzzer", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 } },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 18 } },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 11, "y": 18 } },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MODE FROM $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Safe", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 15, "y": 18 } },
  { "title": "Safe", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 17, "y": 18 } },
  {
   "title": "Safing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SAFE FROM $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT log FROM logs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}