{
 "title": "FL-1 - Control",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Vehicle", "query": "FL_1" },
   { "name": "GroundStationIP", "query": "gs.local" },
   { "name": "GroundStationPort", "query": "8080" },
   {
    "name": "Program",
    "query": "SELECT program from ec_programs"
   }
  ]
 },
 "panels": [
  { "title": "OX Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 } },
  { "title": "OX Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT OX_STR from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 } },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 0 } },
  {
   "title": "Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT CLOCK from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 0 } },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 0 } },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 0 } },
  { "title": "FUEL Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 } },
  { "title": "FUEL Valve", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT FUEL_STR from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 7, "y": 3 } },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 9, "y": 3 } },
  {
   "title": "Hold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HOLD from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 18, "y": 3 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 } },
  { "title": "OX Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 } },
  { "title": "OX Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT OX_PURGE_STR from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Mode", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 7, "y": 6 } },
  {
   "title": "Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MODE FROM $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 } },
  { "title": "Countdown", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 15, "y": 6 } },
  { "title": "Hold", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 19, "y": 6 } },
  { "title": "Clock", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 21, "y": 6 } },
  { "title": "FUEL Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 } },
  { "title": "FUEL Purge", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT FUEL_PURGE_STR from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 7, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Igniter", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 12 } },
  { "title": "Igniter", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 2, "y": 12 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT IGNITER_STR from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Safe", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 8, "y": 12 } },
  { "title": "Safe", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 10, "y": 12 } },
  {
   "title": "Safing",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SAFING FROM $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Program", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 15, "y": 12 } },
  {
   "title": "Sequence",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SEQ_NUM_EC from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT HEARTBEAT from $Vehicle",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 10, "w": 22, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT log FROM logs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logging", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 } },
  { "title": "Logging", "type": "cloudspout-button-panel", "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 } }
 ]
}