all:
	chmod +x start.sh
	chmod +x stop.sh
	chmod +x scripts/reset_admin_pwd.sh
	chmod +x scripts/edit_config.sh

clean:
	chmod -x start.sh
	chmod -x stop.sh
	chmod -x scripts/reset_admin_pwd.sh
	chmod -x scripts/edit_config.sh
