#!/bin/bash

set -e

if ! [ -v GSW_HOME ]
then
    echo environment not set, must run '. setenv' first
fi

# create the pidlist file
if ! [ -f pidlist ]
then
    touch pidlist
else
    echo "GSW is already running!"
    exit
fi

# create shared memory
${GSW_HOME}/proc/shmctl/shmctl -on

# NOTE: PIDs are added to the begining of the file
#       so they are shutdown in the reverse order they started up
#       this keeps the data logger alive as long as possible


# start data logging process
echo "starting data logging process"
${GSW_HOME}/proc/dlp/dlp &
echo $! | cat - pidlist > temp && mv temp pidlist

# start the decom process
echo "starting decom process"
${GSW_HOME}/proc/decom/decom &
echo $! | cat - pidlist > temp && mv temp pidlist
