#!/bin/bash

# ignore failed commands
set +e

# TODO let operator select this
# for now use a default config file
ln -s ../data/sample/config ../data/config

chmod +x ../setenv
chmod +x ../startup/*/start_*
chmod +x ../shutdown/*/shutdown_*
chmod +x ../data/select_config.sh
chmod +x ../log/clean.sh
chmod +x ../log/save.sh
chmod +x ../log/fifo.sh
chmod +x ../startup/select_current.sh

. ../setenv

(cd ..; make all)
