#!/bin/bash

# ignore failed commands
set +e

# TODO let operator select this (make a tool to change eventually)
ln -s ../data/blackout/config ../data/config

chmod +x ../startup/start_*

mkdir ../log
sudo mkdir /gsw
sudo chmod 777 /gsw

chmod +x getdir.py
../setenv
