all:
	g++ -std=c++11 -o analysis analysis.cpp -lstdc++fs -I/usr/include/python3.10 -lpython3.10 -Iinclude

debug:
	g++ -std=c++11 -g -o analysis analysis.cpp -lstdc++fs -I/usr/include/python3.10 -lpython3.10 -Iinclude

clean:
	rm analysis *.pdf
