#!/bin/bash

# abrupt way to kill all gsw processes
# will NOT free any network / file resources first (kill those processes more gracefully)
# ^^^ the decom process has a signal handler to fix this problem

if ! [ -v GSW_HOME ]
then
    echo environment not set, must run '. setenv' first
fi

# stop advertising ourselves over mDNS
echo "stopping mDNS advertisement"
${GSW_HOME}/proc/tool/mdns_publish/mdns_clean.sh mdns_pids

# TODO should probably kill DLP last (after destroying shared memory)
#      not a huge issue though

# BE CAREFUL if copying this file
FILE=${GSW_HOME}/startup/propulsion/pidlist
if ! [ -f $FILE ]
then
    echo "no pidlist file"
    exit
else
    while read l; do
        echo "killing PID $l"
        sudo kill $l
        sleep 1.0 
    done <$FILE
fi

rm $FILE

# destroy shared memory
${GSW_HOME}/proc/shmctl/shmctl -off

# kill the system log FIFO
echo "stopping log FIFO"
${GSW_HOME}/log/fifo.sh -delete

# convert logs to CSV
echo "converting logs to CSV"
${GSW_HOME}/proc/tool/log2csv/log2csv ${GSW_HOME}/log

# save the logs (leave the most recent logs in the log directory)
echo "saving logs"
TIMESTAMP=`date +%Y-%m-%d_%H-%M-%S`
cd ${GSW_HOME}/log
./save.sh $TIMESTAMP

