# Make all process subdirs

all:
	-$(MAKE) -C mkshm all
	-$(MAKE) -C mqueue_test all
	-$(MAKE) -C vcm_test all

clean:
	-$(MAKE) -C mkshm clean
	-$(MAKE) -C mqueue_test clean
	-$(MAKE) -C mqueue_test clean
